eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: serviceZuul
  zipkin:
    base-url: http://localhost:9411
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: serviceRibbon
    api-b:
      path: /api-b/**
      serviceId: serviceFeign
